### PR TITLE
Some fixes and performance resolutions etc etc

### PR DESCRIPTION
**Pull request by Ferlorin**
Add automatically sections that did not exist in the config, back button does not create infinite new Worldbosses.cs etc etc, has a reference to its Owner and calls it back, fixing the bug when opening Timer it used to open as many times as a new forms was opened = every time a button was pressed

### CODE REVIEW

**Comment by Catnoid** [comment]
Probs are solved, i just uploaded the wrong version. Use always the ZIP-FILE!

And big THXi helping me, you are the first and ONLY!

**Comment by Catnoid** [comment]
Ok, look at code and tell me why my timer runs out before midnight and starts then again.
i search now since days 4 an issue and dont find one
________________________________
Von: Ferlorin ***@***.***>
Gesendet: Dienstag, 16. Januar 2024 10:10
An: Catnoid/GW2FOX ***@***.***>
Cc: Catnoid ***@***.***>; Comment ***@***.***>
Betreff: Re: [Catnoid/GW2FOX] Some fixes and performance resolutions etc etc (PR #1)


Ill keep helping and working on things if this is ok with you :D

**Comment by Ferlorin** [comment]
seems the logic was wrong. The timer was always before midnight (23:59), so there was nothing to show. I changed the logic (to also take into account the current date and add for the next date bosses if there are no more remaining on the current date) and added a new class that groups the events and shows the next 2 runs (NEXT_RUNS_TO_SHOW in BossTimings.cs). I also added a new file GlobalVariables.cs that contains some globals so that it is not repeated throughout the code.

If you accept the pull request (before making any changes) i think everything works as expected. You can always revert commit and that will return it to the previous version(s).

You can also give me access to the code to be able to push changes or you can make a new branch and give me access to it so that you can merge easily or leave it as is and I will create pull requests like this one.
Hope you find everything working


//TODO i think we need to add a way to "automatically" mark to which bosses we went and then autoremove them from the active boss list, what do you think?

**Comment by Ferlorin** [comment]
do you wanna accept the pull request?

**Comment by Catnoid** [comment]
I download it testet it and put it into trash - timer dont worx - i have 10.000 past Events.....in strange meaning!
Better to work with an old Version of my tool. THXi 4 trying to help....but that is a desaster

**Comment by Ferlorin** [comment]
Can you attach some screenshots? I didnt face any problem like that. Did you download the latest version? The past events returns only the 1 latest on purpose, unless there is some condition that makes it return that many, but I havent found anything like that until now

**Pull request closed without merging**
